version: '2.4'
services:
  db:
    image: mysql
    container_name: netdeal_backend
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - netdeal_backend:/var/lib/mysql

volumes:
  netdeal_backend: